import '/js/loader.js'
import '/js/faq.js';
import '/js/mobile-menu.js';
import '/js/order-modal.js';
import '/js/notifications';
import '/js/hover-animation.js';
import '/js/pets-list/categories-list.js';
import '/js/pets-list/pet-list.js';
import '/js/pawlist-modal.js';
import '/js/scroll-to-top.js';
